name: NodeJS with Gulp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  FTP_HOST: "ftp.petersonnutrition.com"
  FTP_USER: "admin@petersonnutrition.com"
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Build
      run: |
        npm install
        gulp build
        gulp deploy
